Explicitly depend on the request module
Production is failing to load the transitive dependency for some reason here

Exception: Worker was unable to load function evergreen-upload: 'Error: Cannot find module 'request''
Stack: Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at D:\home\site\wwwroot\evergreen-upload\node_modules\request-promise\lib\rp.js:11:16
    at module.exports (D:\home\site\wwwroot\evergreen-upload\node_modules\stealthy-require\lib\index.js:62:23)
    at Object.<anonymous> (D:\home\site\wwwroot\evergreen-upload\node_modules\request-promise\lib\rp.js:10:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\evergreen-upload\lib\jenkins.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18).